### ISSUE TITLE
Is the SpinSearch plugin file supposed to be a .pdb file?

### ISSUE THREAD

**Issue by Loosiano** [SRXDModdingGroup/SpinSearch#2]
**Describe the bug**
As the title says, my only knowledge with mods is that they are usually supposed to be a .dll file, and I tried changing the extension to be .dll, but that also did not work.

![38404cf18f7a1cf6595589d6a68f2915](https://user-images.githubusercontent.com/97933784/149877730-c16b8f48-f43b-48f1-a554-a34a60b33f40.png)

**Comment by Grub4K** [comment]
I have updated the latest release
